data:
  train_ids: [
    'E12198-23_sample1_half1', 
    'E12198-23_sample1_half2', 
    # 'E12198-23_sample2_half1', 
    # 'E12198-23_sample2_half2', 
    # 'E1223-24_sample1', 
    # 'E1223-24_sample2', 
    # 'E1223-24_sample3', 
    # 'E13557-23_half1', 
    # 'E13557-23_half2', 
    # 'E15356-23_sample1', 
    # 'E15356-23_sample2', 
    # 'E15356-23_sample3', 
    # 'E15356-23_sample4', 
    # 'E15754-23_sample1', 
    # 'E15754-23_sample2', 
    # 'E15754-23_sample3', 
    # 'E17878-23_sample1_half1', 
    # 'E17878-23_sample1_half2', 
    # 'E17878-23_sample2_half1'
  ]
  val_ids: [
    # 'E341-24_sample3',
    # 'E341-24_sample4',
    # 'E341-24_sample5',
    # 'E341-24_sample6',
    # 'E341-24_sample7',
    # 'E119-24_sample1_1-half1', 
    # 'E119-24_sample1_2', 
    # 'E119-24_sample2_1_half1', 
    # 'E119-24_sample2_1_half2', 
    # 'E919-24_sample1_1', 
    # 'E919-24_sample1_2', 
    # 'E919-24_sample2_1', 
    'E919-24_sample2_2'
  ]
  acdc_channels: [3, 26]
  use_srs_norm: True
  extra_filtering: [
    # "E119-24_sample1_1-half1", "E119-24_sample1_2", "E119-24_sample2_1_half1", "E119-24_sample2_1_half2",
    # 'E919-24_sample1_1', 'E919-24_sample2_1', 'E919-24_sample1_2', 'E919-24_sample2_2',
  ]
training:
  patch_size: [ 256, 256 ]
  stride: [ 256, 256 ]
task: 'segment'
name: 'segment_unet_01_newdata'
model:
  type: 'unet'
  latent_dim: 256
  input_dim: 24
  output_dim: 1
  # pretrained_path: "/home/ct678/code/CHARM/saved_models/segment_unet_256_epoch_50.pth"
hyperparams:
  batch_size: 12 # NOTE: different when running on HPC
  n_epochs: 30
